# Generated by Django 5.1 on 2024-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
